name: Scrap games from Xbox Game Pass
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  scrapGames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run scrapGames
      - uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
